[project]
name = 'com.softalks.numbers'
version = '1.0.1b1'
description = 'Writes all the natural numbers to console'
readme = 'README.md'
authors = [
  {name = 'Santiago Ruiz', email = 'hiebra@hotmail.com'}
] 
dependencies = [
    'com.softalks.sh >= 1, < 2'
]