[project]
name = "Natural Numbers Writer"
description = "Writes all the natural numbers to console"
version = "0.0.1"
authors = [
  {name = "Santiago Ruiz", email= "hiebra@hotmail.com"}
]
dependencies = [
    "com.softalks.debug @ git+https://github.com/hiebra/words-py@v0.0.1",
]
[tool.setuptools.packages.find]
where = ["runnable"]